---
- name: "s3 bucket creation"
  gather_facts: no
  connection: local
  become: yes
  hosts: localhost
  vars:
    bucketname: myworkingbucket
    access_key: "***********"
    secret_key: "*********************"
    region: "ap-south-1"

  tasks:
    - name: "installtion of pip module"
      yum:
        name: pip
        state: present
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: "{{ item }}"
      with_items:
        - boto3
        - botocore
    - name: "create a s3 bucket"
      s3_bucket:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        ec2_region: "{{ region }}"
        name: "{{ bucketname }}"
        policy: "{{ lookup( 'file','my_bucket_policy.json' )}}"
        versioning: no
        state: present

    - name: "upload images to the s3bucket"
      s3_sync:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        ec2_region: "{{ region }}"
        bucket: "{{ bucketname }}"
        file_root: /var/deployment/test/
